### PR TITLE
Guarantee that an on_miss callback fulfills a failed get request.

### LINKED ISSUE #122: Guarantee get after on_miss?
There are two recommended ways to use the cache, one of them being supplying an on_miss callback.  Alas, if there's a lot of puts going on (likely if there's a "preload" operation going on a live server) or the callback is very slow after put (writes a log/etc which stalls), it's possible for the entry to have already been evicted before get gets around to retry the request.

And, knowing people, no one is going to check for **that**.  A rare unexpected failure will crash the program.

One way to fix this would be a TLS variable that says we're in an on_miss callback.  The put done by that thread would have its refcount bumped, decreased only once the get completes (there might be more than one put, but only one successful for that specific key).

Thoughts...?

### PR DESCRIPTION
**Pull request by kilobyte**
There are rare cases when the value the user provided wasn't delivered.  Let's not have nasty surprises — this kind of failures is very difficult to test against, and workarounds disrupt the workflow.

As a bonus, this simplifies the on_miss code path and makes it faster.

It affects the stats (wrt #124) — I fixed the non-controversial case of no on_miss; we still need to agree what to return when the callback exists and fails or succeeds.

Fixes #122.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/vmemcache/137)

### CODE REVIEW

File: src/vmemcache.c [hunk 1]
```diff
@@ -225,6 +238,23 @@ int
 vmemcache_put(VMEMcache *cache, const void *key, size_t ksize,
 				const void *value, size_t value_size)
 {
+	if (get_req.key && get_req.ksize == ksize &&
+		memcmp(get_req.key, key, ksize) == 0) {
+
+		get_req.key = NULL; /* mark request as satisfied */
+		if (get_req.offset >= value_size)
```
Comment (pbalcer) [inline src/vmemcache.c]: {}

File: src/vmemcache.c [hunk 2]
```diff
@@ -225,6 +238,23 @@ int
 vmemcache_put(VMEMcache *cache, const void *key, size_t ksize,
 				const void *value, size_t value_size)
 {
+	if (get_req.key && get_req.ksize == ksize &&
```
Comment (pbalcer) [inline src/vmemcache.c]: please move this to a separate function.

File: src/vmemcache.c [hunk 3]
```diff
@@ -406,26 +436,32 @@ vmemcache_get(VMEMcache *cache, const void *key, size_t ksize, void *vbuf,
...
-		ret = vmcache_index_get(cache->index, key, ksize, &entry);
-		if (ret < 0)
-			return -1;
+			(*cache->on_miss)(cache, key, ksize, cache->arg_miss);
 
-		if (entry == NULL)
-			return 0;
-	}
+			if (!get_req.key)
+				return (ssize_t)get_req.vbufsize;
```
Comment (pbalcer) [inline src/vmemcache.c]: Can be distinguish between copying 0 bytes and failing to find the element? I think this should return -1.

File: tests/vmemcache_test_basic.c [hunk 4]
```diff
@@ -384,7 +384,7 @@ on_evict_test_evict_cb(VMEMcache *cache, const void *key, size_t key_size,
 /*
```
Comment (pbalcer) [inline tests/vmemcache_test_basic.c]: we need to add a test where on_miss callback fails to put.
